order = -1
video_url = "https://archival-uploads.jesseditson.com/example.mp4"
copyright_name = "Your Name"
author = "Archival"
home_title = "asdadsa"
name = "Archivalsdsd. sss"
description = "A simple video presentation template."
